[package]
name = "vulkan_runner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
algae = {path = "../algae"}
algae_jit = {path = "../algae_jit"}